### ISSUE TITLE
Is this package usable?

### ISSUE THREAD

**Issue by AStupidBear** [Matt5sean3/GtkBuilderAid.jl#18]

**Comment by Matt5sean3** [comment]
I've been using this package for a while with good results.

The code isn't perfectly stable but I'm planning to not make backwards incompatible changes. If you use this package and it doesn't work as described please submit an issue so I can fix it or, even better, submit a pull request with a fix.

**Comment by Matt5sean3** [comment]
The short answer is yes, you can even install this via Julia's in-built package manager.
